// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { greeting, type Options } from '../sdk.gen';
import type { GreetingData, GreetingError, GreetingResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const greetingQueryKey = (options?: Options<GreetingData>) => createQueryKey('greeting', options);

/**
 * Greeting
 *
 * Return a greeting for ``name``, falling back to a default when blank.
 */
export const greetingOptions = (options?: Options<GreetingData>) => queryOptions<GreetingResponse, GreetingError, GreetingResponse, ReturnType<typeof greetingQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await greeting({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: greetingQueryKey(options)
});
