// This file is auto-generated by @hey-api/openapi-ts

export { greeting, type Options } from './sdk.gen';
export type { ClientOptions, GreetingData, GreetingError, GreetingErrors, GreetingResponse, GreetingResponses, HttpValidationError, MessageResponse, ValidationError } from './types.gen';
