// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AuthJwtCookieLoginData, AuthJwtCookieLoginErrors, AuthJwtCookieLoginResponses, AuthJwtCookieLogoutData, AuthJwtCookieLogoutErrors, AuthJwtCookieLogoutResponses, GreetingData, GreetingErrors, GreetingResponses, RegisterData, RegisterErrors, RegisterResponses, ResetForgotPasswordData, ResetForgotPasswordErrors, ResetForgotPasswordResponses, ResetResetPasswordData, ResetResetPasswordErrors, ResetResetPasswordResponses, UsersCurrentUserData, UsersCurrentUserErrors, UsersCurrentUserResponses, UsersDeleteUserData, UsersDeleteUserErrors, UsersDeleteUserResponses, UsersPatchCurrentUserData, UsersPatchCurrentUserErrors, UsersPatchCurrentUserResponses, UsersPatchUserData, UsersPatchUserErrors, UsersPatchUserResponses, UsersUserData, UsersUserErrors, UsersUserResponses, VerifyRequestTokenData, VerifyRequestTokenErrors, VerifyRequestTokenResponses, VerifyVerifyData, VerifyVerifyErrors, VerifyVerifyResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(options: Options<ResetForgotPasswordData, ThrowOnError>): RequestResult<ResetForgotPasswordResponses, ResetForgotPasswordErrors, ThrowOnError> => (options.client ?? client).post<ResetForgotPasswordResponses, ResetForgotPasswordErrors, ThrowOnError>({
    url: '/api/auth/forgot-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Auth:Jwt-Cookie.Login
 */
export const authJwtCookieLogin = <ThrowOnError extends boolean = false>(options: Options<AuthJwtCookieLoginData, ThrowOnError>): RequestResult<AuthJwtCookieLoginResponses, AuthJwtCookieLoginErrors, ThrowOnError> => (options.client ?? client).post<AuthJwtCookieLoginResponses, AuthJwtCookieLoginErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Auth:Jwt-Cookie.Logout
 */
export const authJwtCookieLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthJwtCookieLogoutData, ThrowOnError>): RequestResult<AuthJwtCookieLogoutResponses, AuthJwtCookieLogoutErrors, ThrowOnError> => (options?.client ?? client).post<AuthJwtCookieLogoutResponses, AuthJwtCookieLogoutErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'papertrailauth',
            type: 'apiKey'
        }],
    url: '/api/auth/logout',
    ...options
});

/**
 * Register
 *
 * Create an account and email a confirmation link.
 *
 * Deliberately does **not** reveal whether the address was already registered:
 * both a fresh creation and an ``UserAlreadyExists`` collision return the same
 * neutral ``202`` so the endpoint can't be used to enumerate accounts. The
 * verification email is sent from ``UserManager.on_after_register``.
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(options: Options<VerifyRequestTokenData, ThrowOnError>): RequestResult<VerifyRequestTokenResponses, VerifyRequestTokenErrors, ThrowOnError> => (options.client ?? client).post<VerifyRequestTokenResponses, VerifyRequestTokenErrors, ThrowOnError>({
    url: '/api/auth/request-verify-token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetResetPasswordData, ThrowOnError>): RequestResult<ResetResetPasswordResponses, ResetResetPasswordErrors, ThrowOnError> => (options.client ?? client).post<ResetResetPasswordResponses, ResetResetPasswordErrors, ThrowOnError>({
    url: '/api/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(options: Options<VerifyVerifyData, ThrowOnError>): RequestResult<VerifyVerifyResponses, VerifyVerifyErrors, ThrowOnError> => (options.client ?? client).post<VerifyVerifyResponses, VerifyVerifyErrors, ThrowOnError>({
    url: '/api/auth/verify',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Greeting
 *
 * Return a greeting for ``name``, falling back to a default when blank.
 */
export const greeting = <ThrowOnError extends boolean = false>(options?: Options<GreetingData, ThrowOnError>): RequestResult<GreetingResponses, GreetingErrors, ThrowOnError> => (options?.client ?? client).get<GreetingResponses, GreetingErrors, ThrowOnError>({ url: '/api/greeting', ...options });

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<UsersCurrentUserData, ThrowOnError>): RequestResult<UsersCurrentUserResponses, UsersCurrentUserErrors, ThrowOnError> => (options?.client ?? client).get<UsersCurrentUserResponses, UsersCurrentUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'papertrailauth',
            type: 'apiKey'
        }],
    url: '/api/users/me',
    ...options
});

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(options: Options<UsersPatchCurrentUserData, ThrowOnError>): RequestResult<UsersPatchCurrentUserResponses, UsersPatchCurrentUserErrors, ThrowOnError> => (options.client ?? client).patch<UsersPatchCurrentUserResponses, UsersPatchCurrentUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'papertrailauth',
            type: 'apiKey'
        }],
    url: '/api/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(options: Options<UsersDeleteUserData, ThrowOnError>): RequestResult<UsersDeleteUserResponses, UsersDeleteUserErrors, ThrowOnError> => (options.client ?? client).delete<UsersDeleteUserResponses, UsersDeleteUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'papertrailauth',
            type: 'apiKey'
        }],
    url: '/api/users/{id}',
    ...options
});

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(options: Options<UsersUserData, ThrowOnError>): RequestResult<UsersUserResponses, UsersUserErrors, ThrowOnError> => (options.client ?? client).get<UsersUserResponses, UsersUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'papertrailauth',
            type: 'apiKey'
        }],
    url: '/api/users/{id}',
    ...options
});

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(options: Options<UsersPatchUserData, ThrowOnError>): RequestResult<UsersPatchUserResponses, UsersPatchUserErrors, ThrowOnError> => (options.client ?? client).patch<UsersPatchUserResponses, UsersPatchUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'papertrailauth',
            type: 'apiKey'
        }],
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
