// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageResponse
 *
 * A simple ``{"message": ...}`` envelope for endpoints without a resource body.
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GreetingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string;
    };
    url: '/api/greeting';
};

export type GreetingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GreetingError = GreetingErrors[keyof GreetingErrors];

export type GreetingResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type GreetingResponse = GreetingResponses[keyof GreetingResponses];
