#!/usr/bin/env bash
set -euo pipefail

# devcontainer `initializeCommand`: runs on the HOST before the container is
# created/started - for BOTH `scripts/agent.sh` and VS Code "Reopen in
# Container", so git works regardless of how the container is brought up.
#
# A git worktree's `.git` is a *file* pointing at the main repo's git dir,
# which holds the objects/refs/index and lives OUTSIDE the worktree - so it is
# not part of the `..:/workspace` mount. Without it, in-container git fails
# with "fatal: not a git repository". We can't hardcode that path (the repo may
# be cloned anywhere, under any folder name), so we compute it here and emit a
# compose override that bind-mounts it at the SAME absolute path, letting the
# worktree's existing pointer resolve as-is. For the main checkout this is just
# the repo's own `.git` - a harmless identity mount.
#
# The generated file is host-specific and git-ignored; it is regenerated on
# every container (re)build so it always matches the current machine.

cd "$(dirname "${BASH_SOURCE[0]}")/.."   # workspace folder (parent of .devcontainer)

git_common_dir="$(cd "$(git rev-parse --git-common-dir)" && pwd)"

cat > .devcontainer/docker-compose.git.yml <<YAML
# Generated by .devcontainer/gen-git-mount.sh - do not edit or commit.
# Bind-mounts the git common dir so in-container git works from a worktree.
services:
  app:
    volumes:
      - ${git_common_dir}:${git_common_dir}
YAML
