"""Generate a Markdown review checklist of every file worth reviewing in the repo.

The repo was largely "vibe-coded"; this produces a single ``REVIEW_TODO.md`` that
lists every git-tracked, non-auto-generated file as a clickable link, grouped into
a folder tree. Both folders and files get a checkbox so a reviewer can tick each
one off as they go.

The file set comes from ``git ls-files`` (so ``.gitignore`` is honoured for free:
``node_modules``, ``.venv``, caches, and the generated ``routeTree.gen.ts`` never
appear). Auto-generated, vendored, and binary files are then filtered out of the
checklist and listed separately in an "Excluded" appendix so nothing is silently
dropped.

Usage::

    uv run python scripts/generate_review_todo.py [OUTPUT]

``OUTPUT`` defaults to ``REVIEW_TODO.md`` at the repo root.
"""

import argparse
import datetime
import shutil
import subprocess
import sys
from fnmatch import fnmatch
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent

# --- What to leave out of the checklist -----------------------------------
# Grouped by *why* so the appendix can explain each exclusion. Edit these to
# taste and re-run; the rules are deliberately explicit rather than clever.

# Mechanically produced from other sources; the quality gate regenerates them.
_GENERATED_EXACT = frozenset({"openapi.json", "uv.lock"})
_GENERATED_DIR_PREFIXES = ("frontend/src/client/",)  # @hey-api generated client
_GENERATED_SUFFIXES = (".gen.ts",)
_GENERATED_NAME_GLOBS = ("pnpm-lock.yaml", "*-lock.json")  # lockfiles

# Third-party code copied in verbatim and kept pristine (review upstream).
_VENDORED_DIR_PREFIXES = ("frontend/src/components/ui/",)  # shadcn/ui

# Not reviewable as source text.
_ASSET_SUFFIXES = (
    ".ico",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".svg",
    ".woff",
    ".woff2",
    ".ttf",
    ".otf",
    ".pdf",
)
_NON_CODE_EXACT = frozenset({"LICENSE"})

# Reason key -> appendix section heading, in the order they should appear.
_EXCLUSION_SECTIONS: tuple[tuple[str, str], ...] = (
    ("generated", "Auto-generated — produced by tooling, regenerated by the gate"),
    ("vendored", "Vendored third-party — kept pristine; review upstream, not here"),
    ("binary", "Binary / asset files — not reviewable as text"),
    ("license", "License text — standard boilerplate, not project code"),
)

# A file's own path in the tree links to itself; every node is a checkbox.
type Tree = dict[str, "Tree"]


def classify(path: str) -> str | None:
    """Return the exclusion reason for ``path``, or ``None`` if it needs review."""
    name = path.rsplit("/", 1)[-1]
    if (
        path in _GENERATED_EXACT
        or path.startswith(_GENERATED_DIR_PREFIXES)
        or path.endswith(_GENERATED_SUFFIXES)
        or any(fnmatch(name, pattern) for pattern in _GENERATED_NAME_GLOBS)
    ):
        return "generated"
    if path.startswith(_VENDORED_DIR_PREFIXES):
        return "vendored"
    if path.endswith(_ASSET_SUFFIXES):
        return "binary"
    if path in _NON_CODE_EXACT:
        return "license"
    return None


def tracked_files() -> list[str]:
    """List every git-tracked file, repo-relative, sorted."""
    git = shutil.which("git")
    if git is None:
        sys.exit("error: git executable not found on PATH")
    result = subprocess.run(  # noqa: S603 - fixed args, resolved git path, no shell
        [git, "ls-files"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return sorted(result.stdout.splitlines())


def build_tree(paths: list[str]) -> Tree:
    """Build a nested name->children tree from ``a/b/c`` paths (files are leaves)."""
    root: Tree = {}
    for path in paths:
        node = root
        for part in path.split("/"):
            node = node.setdefault(part, {})
    return root


def _sorted_children(node: Tree) -> list[tuple[str, Tree]]:
    """Order a node's children: directories first, then files, each alphabetically."""
    return sorted(node.items(), key=lambda item: (not item[1], item[0].lower()))


def render_tree(node: Tree, prefix: str, depth: int, lines: list[str]) -> None:
    """Append the checklist lines for ``node`` (a directory) to ``lines``."""
    indent = "  " * depth
    for name, child in _sorted_children(node):
        rel = f"{prefix}{name}"
        if child:  # non-empty children -> a directory
            lines.append(f"{indent}- [ ] **{name}/**")
            render_tree(child, f"{rel}/", depth + 1, lines)
        else:  # leaf -> a file, linked to itself
            lines.append(f"{indent}- [ ] [{name}]({rel})")


def count_folders(paths: list[str]) -> int:
    """Count the distinct directories that contain at least one reviewed file."""
    folders: set[str] = set()
    for path in paths:
        parts = path.split("/")[:-1]
        for depth in range(1, len(parts) + 1):
            folders.add("/".join(parts[:depth]))
    return len(folders)


def render_excluded(excluded: list[tuple[str, str]]) -> list[str]:
    """Render the appendix listing excluded files grouped by reason."""
    lines = ["## Excluded from review", ""]
    lines.append("Tracked files intentionally left off the checklist above.")
    lines.append("")
    for reason, heading in _EXCLUSION_SECTIONS:
        section = sorted(path for path, why in excluded if why == reason)
        if not section:
            continue
        lines.append(f"### {heading}")
        lines.append("")
        lines.extend(f"- [{path}]({path})" for path in section)
        lines.append("")
    return lines


def build_document(review: list[str], excluded: list[tuple[str, str]]) -> str:
    """Assemble the full Markdown document."""
    today = datetime.datetime.now(tz=datetime.UTC).date().isoformat()
    folders = count_folders(review)
    lines = [
        "# Code review TODO",
        "",
        f"_Generated by `scripts/generate_review_todo.py` on {today}. "
        "Re-run it to refresh the file list; your ticks are not preserved._",
        "",
        "A full-review checklist for the vibe-coded `papertrail` repo. Every tracked, "
        "non-auto-generated file is listed as a clickable link. Tick a file when "
        "you've reviewed it; tick a folder once everything under it is done.",
        "",
        f"**{len(review)} files** to review across **{folders} folders** "
        f"(plus {len(excluded)} excluded — see the appendix).",
        "",
        "## Files to review",
        "",
    ]
    render_tree(build_tree(review), "", 0, lines)
    lines.append("")
    lines.extend(render_excluded(excluded))
    return "\n".join(lines).rstrip("\n") + "\n"


def parse_output_path() -> Path:
    """Parse CLI args and return the resolved output path."""
    parser = argparse.ArgumentParser(
        description="Generate the code-review TODO checklist."
    )
    parser.add_argument(
        "output",
        nargs="?",
        default="REVIEW_TODO.md",
        help="output Markdown file (default: REVIEW_TODO.md at the repo root)",
    )
    output = Path(parser.parse_args().output)
    return output if output.is_absolute() else _REPO_ROOT / output


def main() -> None:
    """Generate the review checklist and write it to the chosen output file."""
    review: list[str] = []
    excluded: list[tuple[str, str]] = []
    for path in tracked_files():
        reason = classify(path)
        if reason is None:
            review.append(path)
        else:
            excluded.append((path, reason))

    output = parse_output_path()
    output.write_text(build_document(review, excluded), encoding="utf-8")

    rel = (
        output.relative_to(_REPO_ROOT) if output.is_relative_to(_REPO_ROOT) else output
    )
    sys.stdout.write(
        f"Wrote {rel}: {len(review)} files to review, {len(excluded)} excluded.\n",
    )


if __name__ == "__main__":
    main()
